version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.web
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - api

  db:
    image: postgres:14.9
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.php
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  app:
    build:
      context: ./vue-app
      dockerfile: Dockerfile.vue
    volumes:
      - ./vue-app:/app
    ports:
      - "8080:80"

  # web:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app
  #     - api

volumes:
  pgdata: