version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
      # - vuebuilder

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.php
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14.9
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  vue:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile.vue
    volumes:
      - .:/app
    ports:
      - "8081:8080"

volumes:
  pgdata:
  # vue-dist:
